# Generated by Django 4.0.6 on 2022-07-08 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 4, 15, 27, 59145, tzinfo=utc)),
        ),
    ]
