# Generated by Django 4.0.6 on 2022-07-09 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todotask_due_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 6, 57, 11, 376698, tzinfo=utc)),
        ),
    ]
